package by.epam.likeit.controller.helper;

public enum  CommandName {
    LOGIN, LOGOUT, LOCALE, REGISTRATION, LAST_QUESTIONS, ADD_QUESTION, ALL_TOPICS, DELETE_QUESTION, GET_QUESTION, ADD_ANSWER,
    DELETE_ANSWER, SET_RATING, EDIT_QUESTION, GET_USER_RATING, CHANGE_PASSWORD, CHANGE_IMAGE, EDIT_PROFILE,
    ADD_TOPIC, EDIT_TOPIC, DELETE_TOPIC, GET_TOPICS, NEXT_QUESTIONS
}
