package by.epam.likeit.controller.helper;

public enum  CommandName {
    LOGIN, LOGOUT, LOCALE, REGISTRATION, LAST, ADD_QUESTION, ALL_TOPICS, DELETE_QUESTION, GET_QUESTION, ADD_ANSWER,
    DELETE_ANSWER, SET_RATING, EDIT_QUESTION, GET_USER_RATING
}
